name: CI

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v3


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Server
      run:  go build -ldflags="-s -w" -o app .
      working-directory: ./
      

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: checkIPRecord-artifact
       path: ${{ github.workspace }}/app

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
       name: checkIPRecord-artifact
    
